### ISSUE TITLE
Add a simple favicon

### ISSUE THREAD

**Issue by tramyardg** [tramyardg/autoexpress#17]

**Comment by scriptjumper** [comment]
Hi @tramyardg 

Where do you need the favicon

**Comment by tramyardg** [comment]
@shaeenk at home page (index) and also details.php

**Comment by scriptjumper** [comment]
view https://github.com/tramyardg/autoexpress/pull/18 for the logo

**Comment by tramyardg** [comment]
@shaeenk Thanks for the logo 👍
