### ISSUE TITLE
When adding vehicles to the inventory, upload photo function does not work

### ISSUE THREAD

**Issue by StealthWire** [tramyardg/autoexpress#22]
Upload photo function does not work when you add vehicles to the inventory and reach page number 2 of admin "manage vehicle" panel. The page simply refreshes when you click on "upload/delete" photos.

**Comment by StealthWire** [comment]
Further investigation reveals that URL changes visibly to: http://localhost/autoexpress/admin/inventory.php?id=29 

which is not the case with cars listed on 1st page of "manage vehicles". And thanks for the project though.

**Comment by tramyardg** [comment]
Thanks for investigating. I'll look into this, maybe I haven't committed my local copy which might explain this GitHub version is buggy.

**Comment by StealthWire** [comment]
![screenshot 2019-01-23 at 10 31 22 pm](https://user-images.githubusercontent.com/16495675/51623484-cd1b0e00-1f5e-11e9-95a4-b94d81c98c0e.png)

Just to clarify, this is the paging I am talking about. I am fairly new to github btw so excuse if I am not following some protocols and being too pestering. 

I thought that maybe I broke the DB, so I refreshed the DB and added all the vehicles again, but the bug crept back again, so it suggest that the paging php file has some issue. You're the expert tho, waiting for your fix as I am trying to develop this widely and then contributing to it. Thanks and cheers.

**Comment by tramyardg** [comment]
Ok so I added a new car, then I tried to upload a photo. For some reason, the modal for uploading photo(s) is not showing up when I click the button for uploading. This only happens for the newly added car. It's weird.

**Comment by StealthWire** [comment]
For me, the modal opens up on first "1" page of vehicle inventory management but as list gets bigger and goes to second "2" page then the modal just stops to pop up. Instead the page simply refreshes as if "a href=#"

**Comment by tramyardg** [comment]
Yeah you're right!

**Comment by tramyardg** [comment]
I think the pager is causing the problem. I disabled it and the pop up (modal) is now showing, but still cannot upload photos.

**Comment by StealthWire** [comment]
From where did you disable the pager? inventory.php? 
I will give it a shot thereon.

**Comment by tramyardg** [comment]
So yeah it was the pager, uploading photo works, as well as updating and deleting.

**Comment by StealthWire** [comment]
Okay good to know that it seems to be fixed. Did you make changes to the pager file or disabled it completely?

**Comment by tramyardg** [comment]
The pager is here `admin/js/routine/common-html.js`. Line 97-103. 

```js
                    carTableSel.DataTable({
                        "pageLength": 5,
                        "lengthChange": false,
                        searching: false,
                        // "bInfo": false,
                        "aoColumnDefs": [{ 'bSortable': false, 'aTargets': [2, 8] }]
                    });
`

**Comment by tramyardg** [comment]
I'm using Datatables for pager, I haven't tried other tools for paging. This might be a good opportunity to find an alternative.

**Comment by StealthWire** [comment]
> The pager is here `admin/js/routine/common-html.js`. Line 97-103.
> 
> ```js
>                     carTableSel.DataTable({
>                         "pageLength": 5,
>                         "lengthChange": false,
>                         searching: false,
>                         // "bInfo": false,
>                         "aoColumnDefs": [{ 'bSortable': false, 'aTargets': [2, 8] }]
>                     });
> `
> ```

should I simply comment out these lines?

**Comment by StealthWire** [comment]
> I'm using Datatables for pager, I haven't tried other tools for paging. This might be a good opportunity to find an alternative.

I agree. Will save the hassle completely

**Comment by tramyardg** [comment]
`common-html.js` was the only file I changed. I just commented it.

**Comment by StealthWire** [comment]
> `common-html.js` was the only file I changed. I just commented it.

Do you mean you commented lines 97-103 ? Because that does not seem to help me.

**Comment by tramyardg** [comment]
Yeah that's what I did unless there's more than just disabling the pager. I'll commit my changes.

**Comment by StealthWire** [comment]
Ok. Great.

**Comment by tramyardg** [comment]
So I cloned the repo from scratch and tried uploading photo and it works. To view a recently uploaded photo you can go back to index page `http://localhost/autoexpress1/index.php?page=2`
![image](https://user-images.githubusercontent.com/5623994/51628309-b2bb4300-1f12-11e9-87e2-f079f1a811d0.png)
