### ISSUE TITLE
car image not showing on index

### ISSUE THREAD

**Issue by Ibal0512** [tramyardg/autoexpress#29]
car image not showing on index.
Requested URI too long

**Comment by tramyardg** [comment]
@Ibal0512 Tested the app (see the image below) following my setup instruction. 
Fixes https://github.com/tramyardg/autoexpress/commit/94e334acc94feaa88fe77a54500d45ed4a435ec8 and https://github.com/tramyardg/autoexpress/commit/e2d1e98c88429ad780b60af9d3225085becb4d2c

It's working just fine, please use `schema.sql` to recreate your tables.

![image](https://user-images.githubusercontent.com/5623994/68439828-098ac400-0197-11ea-83e9-64434fefa25d.png)

**Comment by Ibal0512** [comment]
Hello, i tried it with the new schema.sql created table but still got the
same error, perhaps it was from my server but i managed to fix it this way.
[image: Captured.PNG]
Thanks alot
